### ISSUE TITLE
LDAP guest binding necessary?

### ISSUE THREAD

**Issue by mattferris** [smonaica/samba-ad-dc#28]
Can this be turned off?

**Comment by lukebarone** [comment]
I'm trying to search for this issue, but not finding too much information. Is there any more information from your scans that we can look for? Is it on the File Server or the Domain Controller or both?

**Comment by mattferris** [comment]
I don't think this can be turned off. Clients are expected to anonymously bind to LDAP on 389, and then (I think) do an authenticated bind to the fancy "Microsoft Global Catalog" on port 3268. Not worth digging into further for now.
