### ISSUE TITLE
Public Wireless Config Change

### ISSUE THREAD

**Issue by lukebarone** [smonaica/samba-ad-dc#35]
After posting to the FreeRADIUS mailing list ([Webpage I was told to follow](http://deployingradius.com/documents/configuration/active_directory.html)), it appears that we need to use MSCHAPv2, instead of PAP. This change needs to happen in the wireless controller.

Wireless Controller -> Authentication -> Default -> Authentication Method -> MSCHAPv2

/etc/freeradius/3.0/mods-enabled/mschap:

Uncomment the `ntlm_auth` line, and edit it to the following (replace `SFG` with your domain):

`ntlm_auth = "/usr/bin/ntlm_auth --request-nt-key --username=%{%{Stripped-User-Name}:-%{%User-Name}:-None}} --domain=%{%mschap:NT-domain}:-SFG} --challenge=%{%{mschap:Challenge}:-00}  --nt-response=%{%{mschap:NT-Response}:-00}"`

Remove the two winbind lines or comment them out:

```
# winbind_username = "%{mschap:User-Name}"
# winbind_domain = "SFG"
```

`/etc/freeradius/3.0/sites-enabled/{default,inner-tunnel}`:

Under the `authorize` stanza, add "ntlm_auth" after the initial open brace.

`/mods-enabled/ntlm_auth`:

Change the `program = ` line to point to `/usr/bin/ntlm_auth`, and add the `--domain=SFG` switch just before `--username=`.

----

Matt F, is there any security issue following this method? It seems to work now, and still honours the users in the `wifiblocked` group on fs1

**Comment by smonaica** [comment]
Thanks for all this Luke, but we had already figured all of this out. It's documented in [FreeRADIUS-Auth-In-AD.md](https://github.com/smonaica/samba-ad-dc/blob/master/FreeRADIUS-Auth-In-AD.md).

The controller at SFG was recently reset, and I just mindless reconfigured it using our Wireless Config guide, which instructs us to use PAP. I had not yet gotten around to applying the changes documented in the [FreeRADIUS-Auth-In-AD.md](https://github.com/smonaica/samba-ad-dc/blob/master/FreeRADIUS-Auth-In-AD.md) doc.

Sorry you had to waste time on this! I should have left a note on the controller, or something.

**Comment by smonaica** [comment]
Just a quick correction to my previous comment. It looks like an essential bit of config for the wifi controller was omitted from our FreeRADIUS-Auth-In-AD.md doc. Luke already pointed it out, but here it is again:

Wireless Controller -> Authentication -> Default -> Authentication Method -> MSCHAPv2

I will add a section in our doc for this. Thanks again, Luke.
