### ISSUE TITLE
NextCloud: Prevent users from editing root directory

### ISSUE THREAD

**Issue by lukebarone** [smonaica/samba-ad-dc#44]
As described in a FirstClass thread, NextCloud users can edit their NextCloud directories, which would cause disk usage to likely go up on the NextCloud server.

The suggestion of locking `/usr/local/share/nextcloud` failed, the user could not log on.

The next suggestion was to follow the recommendation on https://docs.nextcloud.com/server/11/admin_manual/configuration_files/files_access_control.html, specifically:

Try creating an access rule like this:

User group membership    -    is not a member of     -    Administrators

We need someone to assign this permission (or some variant of it), test it, and report back.

**Comment by kibade** [comment]
I had a light bulb moment. We limited this in the early owncloud days in the admin account, under users. I have in my notes we set the default quota to 0M, but nextcloud doesn't allow 0, the lowest seems to be  1 Byte, which to me is the same thing. I've did this just now for hhld. If accepted I'll add this to the nextcloud doc on github.

**Comment by lukebarone** [comment]
This seems to work. I cannot upload files that contain *any* data whatsoever, even using the Sync client
